### ISSUE TITLE
Join Qiskit ecosystem

### ISSUE THREAD

**Issue by frankharkins** [vm6502q/qiskit-qrack-provider#11]
Thanks for maintaining the Qiskit Qrack provider. Would you be interested in submitting it to the Qiskit ecosystem? It'd put the package in front of more users and on our radar so we know how Qiskit is being used. There's also the opportunity to present at a demo day and we'll sometimes reach out to offer support when changes happen in Qiskit.

Links:
* [Ecosystem web page](https://www.ibm.com/quantum/ecosystem)
* [Submission form](https://github.com/Qiskit/ecosystem/issues/new?template=submission.yml)

**Comment by WrathfulSpatula** [comment]
Thanks for checking in! I'll take a look at the forms. Let me make sure that we're up-to-date with current back end implementation standards for the Qiskit API, as well.
